# Generated by Django 2.1.8 on 2019-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('catalogue_number', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('main_image', models.ImageField(upload_to='')),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
