# Generated by Django 5.2.3 on 2025-06-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_auto_20190421_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
