# Generated by Django 5.2.3 on 2025-06-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0005_alter_building_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="buildingimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
