# Generated by Django 5.2.3 on 2025-06-15 20:14

import taggit_autosuggest.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0006_alter_building_id_alter_buildingimage_id"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="tags",
            field=taggit_autosuggest.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
